### ISSUE TITLE
[Plan] All Hands London 2016

### ISSUE THREAD

**Issue by Gioyik** [Gioyik/Web2Board#21]
List of goals to accomplish during All Hands London 2016.
- [ ] Define name for the project (Web2Board is too bad)
- [ ] Documentation about the project
- [ ] Vagrant box for Web2Board project
- [ ] Exploration of API exposure
- [ ] Discuss Gecko embed process
- [ ] Discuss about Servo embed process
- [ ] Research about Raspberry PI 3

JUST DO IT!
